### ISSUE TITLE
Release of v0.5.4 on pypi and on conda-forge

### ISSUE THREAD

**Issue by matteoaletti** [s1tools/s1-etad#1]
Would it be possible to have a release of the v0.5.4 on pypi and on conda-forge? 
The main reason for the new release is to have the latest fixes available through pip.
The reason for having it on conda-forge would be to be able to include this package as a dependency in other projects that provide conda packages.

**Comment by avalentino** [comment]
New version available on PyPI.
Conda recipe in preparation at https://github.com/conda-forge/staged-recipes/pull/25339

**Comment by matteoaletti** [comment]
Thank you!
